// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace POS.Mapping
{
    using POS.Entities;

    // AdminRes
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class AdminReMapping : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<AdminRe>
    {
        public AdminReMapping()
            : this("dbo")
        {
        }

        public AdminReMapping(string schema)
        {
            ToTable("AdminRes", schema);
            HasKey(x => x.AdId);

            Property(x => x.AdId).HasColumnName(@"ad_id").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(10).HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.Username).HasColumnName(@"username").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.Pass).HasColumnName(@"pass").HasColumnType("varchar(max)").IsRequired().IsUnicode(false);
            Property(x => x.Name).HasColumnName(@"name").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.AdRole).HasColumnName(@"ad_role").HasColumnType("int").IsRequired();
            Ignore(x => x.DecryptedPass);
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
