// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace POS.Mapping
{
    using POS.Entities;

    // ApplicationLog
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class ApplicationLogMapping : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<ApplicationLog>
    {
        public ApplicationLogMapping()
            : this("dbo")
        {
        }

        public ApplicationLogMapping(string schema)
        {
            ToTable("ApplicationLog", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.DateAdded).HasColumnName(@"date_added").HasColumnType("datetime").IsRequired();
            Property(x => x.Comment).HasColumnName(@"comment").HasColumnType("ntext").IsRequired().IsMaxLength();
            Property(x => x.ApplicationName).HasColumnName(@"application_name").HasColumnType("nvarchar").IsOptional().HasMaxLength(100);
            Property(x => x.LastUpdatedOn).HasColumnName(@"last_updated_on").HasColumnType("timestamp").IsRequired().IsFixedLength().HasMaxLength(8).IsRowVersion().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Computed);
            Property(x => x.ExtraData).HasColumnName(@"extra_data").HasColumnType("xml").IsOptional();
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
