// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace POS.Mapping
{
    using POS.Entities;

    // Chair
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class ChairMapping : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Chair>
    {
        public ChairMapping()
            : this("dbo")
        {
        }

        public ChairMapping(string schema)
        {
            ToTable("Chair", schema);
            HasKey(x => x.ChairId);

            Property(x => x.ChairId).HasColumnName(@"chair_id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.ChairNumber).HasColumnName(@"chair_number").HasColumnType("int").IsRequired();
            Property(x => x.TableOwned).HasColumnName(@"table_owned").HasColumnType("int").IsOptional();

            // Foreign keys
            HasOptional(a => a.Table).WithMany(b => b.Chairs).HasForeignKey(c => c.TableOwned).WillCascadeOnDelete(false); // fk_table_owned
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
