// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace POS.Mapping
{
    using POS.Entities;

    // OrderNoteDetails
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class OrderNoteDetailMapping : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<OrderNoteDetail>
    {
        public OrderNoteDetailMapping()
            : this("dbo")
        {
        }

        public OrderNoteDetailMapping(string schema)
        {
            ToTable("OrderNoteDetails", schema);
            HasKey(x => new { x.OrdernoteId, x.ProductId });

            Property(x => x.OrdernoteId).HasColumnName(@"ordernote_id").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(10).HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.ProductId).HasColumnName(@"product_id").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(10).HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.Quan).HasColumnName(@"quan").HasColumnType("int").IsRequired();
            Property(x => x.Discount).HasColumnName(@"discount").HasColumnType("int").IsRequired();

            // Foreign keys
            HasRequired(a => a.OrderNote).WithMany(b => b.OrderNoteDetails).HasForeignKey(c => c.OrdernoteId).WillCascadeOnDelete(false); // FK_dbo.OrderNoteDetails_dbo.OrderNote_ordernote_id
            HasRequired(a => a.Product).WithMany(b => b.OrderNoteDetails).HasForeignKey(c => c.ProductId).WillCascadeOnDelete(false); // FK_dbo.OrderNoteDetails_dbo.Product_product_id
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
