// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace POS.Mapping
{
    using POS.Entities;

    // Product
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class ProductMapping : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Product>
    {
        public ProductMapping()
            : this("dbo")
        {
        }

        public ProductMapping(string schema)
        {
            ToTable("Product", schema);
            HasKey(x => x.ProductId);

            Property(x => x.ProductId).HasColumnName(@"product_id").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(10).HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.Name).HasColumnName(@"name").HasColumnType("nvarchar").IsRequired().HasMaxLength(50);
            Property(x => x.Info).HasColumnName(@"info").HasColumnType("nvarchar").IsOptional().HasMaxLength(100);
            Property(x => x.Price).HasColumnName(@"price").HasColumnType("money").IsRequired().HasPrecision(19,4);
            Property(x => x.Type).HasColumnName(@"type").HasColumnType("int").IsRequired();
            Property(x => x.Deleted).HasColumnName(@"deleted").HasColumnType("int").IsRequired();
            Property(x => x.ImageLink).HasColumnName(@"ImageLink").HasColumnType("nvarchar(max)").IsOptional();
            Property(x => x.Discount).HasColumnName(@"Discount").HasColumnType("int").IsRequired();
            Property(x => x.StandardStats).HasColumnName(@"std_stats").HasColumnType("nvarchar").HasMaxLength(50).IsRequired();
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
