// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace POS.Mapping
{
    using POS.Entities;

    // Table
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class TableMapping : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Table>
    {
        public TableMapping()
            : this("dbo")
        {
        }

        public TableMapping(string schema)
        {
            ToTable("Table", schema);
            HasKey(x => x.TableId);

            Property(x => x.TableId).HasColumnName(@"table_id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.TableNumber).HasColumnName(@"table_number").HasColumnType("int").IsRequired();
            Property(x => x.ChairAmount).HasColumnName(@"chair_amount").HasColumnType("int").IsRequired();
            Property(x => x.PosX).HasColumnName(@"pos_X").HasColumnType("int").IsRequired();
            Property(x => x.PosY).HasColumnName(@"pos_Y").HasColumnType("int").IsRequired();
            Property(x => x.IsPinned).HasColumnName(@"is_Pinned").HasColumnType("int").IsRequired();
            Property(x => x.IsOrdered).HasColumnName(@"is_Ordered").HasColumnType("int").IsRequired();
            Property(x => x.IsLocked).HasColumnName(@"is_Locked").HasColumnType("int").IsRequired();
            Property(x => x.IsPrinted).HasColumnName(@"is_Printed").HasColumnType("int").IsRequired();
            Ignore(x => x.TableRec);
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
