// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace POS.Mapping
{
    using POS.Entities;

    // WareHouse
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class WareHouseMapping : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<WareHouse>
    {
        public WareHouseMapping()
            : this("dbo")
        {
        }

        public WareHouseMapping(string schema)
        {
            ToTable("WareHouse", schema);
            HasKey(x => x.WarehouseId);

            Property(x => x.WarehouseId).HasColumnName(@"warehouse_id").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(10).HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.Contain).HasColumnName(@"contain").HasColumnType("float").IsOptional();
            Property(x => x.StandardContain).HasColumnName(@"std_contain").HasColumnType("float").IsRequired();

            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
