// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace POS.Mapping
{
    using POS.Entities;

    // WorkingHistory
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class WorkingHistoryMapping : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<WorkingHistory>
    {
        public WorkingHistoryMapping()
            : this("dbo")
        {
        }

        public WorkingHistoryMapping(string schema)
        {
            ToTable("WorkingHistory", schema);
            HasKey(x => x.WhId);

            Property(x => x.WhId).HasColumnName(@"wh_id").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(10).HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.ResultSalary).HasColumnName(@"result_salary").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(10);
            Property(x => x.EmpId).HasColumnName(@"emp_id").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(10);
            Property(x => x.StartTime).HasColumnName(@"startTime").HasColumnType("datetime").IsRequired();
            Property(x => x.EndTime).HasColumnName(@"endTime").HasColumnType("datetime").IsRequired();

            // Foreign keys
            HasOptional(a => a.Employee).WithMany(b => b.WorkingHistories).HasForeignKey(c => c.EmpId).WillCascadeOnDelete(false); // FK_dbo.WorkingHistory_dbo.Employee_emp_id
            HasOptional(a => a.SalaryNote).WithMany(b => b.WorkingHistories).HasForeignKey(c => c.ResultSalary).WillCascadeOnDelete(false); // FK_dbo.WorkingHistory_dbo.SalaryNote_result_salary
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
