// <auto-generated />
namespace POS.Context
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addproducttype : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addproducttype));
        
        string IMigrationMetadata.Id
        {
            get { return "201711060248447_addproducttype"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
