// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6

using System;

#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace POS.Entities
{

    // OrderNote
    [Serializable]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class StockOut
    {
        public string StockOutId { get; set; } // stockout_id (Primary key) (length: 10)
        public string Adid { get; set; } // ad_id (length: 10)
        public System.DateTime Outtime { get; set; } // outTime
        public decimal Vat { get; set; }    // Vat
        public int Discount { get; set; }       // discount
        public decimal TotalAmount { get; set; } // total_price

        // Reverse navigations
        
        public virtual System.Collections.Generic.ICollection<StockOutDetails> StockOutDetails { get; set; }

        // Foreign keys
        public virtual AdminRe AdminRe { get; set; }

        public StockOut()
        {
            StockOutDetails = new System.Collections.Generic.List<StockOutDetails>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
