// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace POS.Entities
{

    // StockIn
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class StockIn
    {
        public string Si_id { get; set; } // si_id (Primary key) (length: 10)
        public string AdId { get; set; } // ad_id (length: 10)
        public System.DateTime InTime { get; set; } // intime
        public decimal TotalAmount { get; set; } // total_amount

        // Reverse navigation
        public virtual System.Collections.Generic.ICollection<StockInDetails> StockInDetails { get; set; } // ReceiptNoteDetails.FK_dbo.ReceiptNoteDetails_dbo.ReceiptNote_rn_id

        // Foreign keys
        public virtual AdminRe AdminRe { get; set; }

        public StockIn()
        {
            StockInDetails = new System.Collections.Generic.List<StockInDetails>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
