// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


using System.ComponentModel.DataAnnotations;

namespace POS.Entities
{

    // Chair
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class Chair
    {
        [Key]
        public int ChairId { get; set; } // chair_id (Primary key) (length: 10)
        public int ChairNumber { get; set; } // chair_number
        public int TableOwned { get; set; } // table_owned (length: 10)

        // Reverse navigation

        /// <summary>
        /// Child OrderDetailsTemps where [OrderDetailsTemp].[chair_id] point to this entity (fk_chair_id_orderdetailtemp)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<OrderDetailsTemp> OrderDetailsTemps { get; set; } // OrderDetailsTemp.fk_chair_id_orderdetailtemp

        // Foreign keys

        /// <summary>
        /// Parent Table pointed by [Chair].([TableOwned]) (fk_table_owned)
        /// </summary>
        public virtual Table Table { get; set; } // fk_table_owned

        public Chair()
        {
            OrderDetailsTemps = new System.Collections.Generic.List<OrderDetailsTemp>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
