// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace POS.Entities
{

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class GetEmployeeDetailsReturnModel
    {
        public System.String emp_id { get; set; }
        public System.String manager { get; set; }
        public System.String username { get; set; }
        public System.String pass { get; set; }
        public System.String name { get; set; }
        public System.DateTime birth { get; set; }
        public System.DateTime startday { get; set; }
        public System.Int32 hour_wage { get; set; }
        public System.String addr { get; set; }
        public System.String email { get; set; }
        public System.String phone { get; set; }
        public System.Int32 emp_role { get; set; }
        public System.Int32 deleted { get; set; }
    }

}
// </auto-generated>
