// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


using System.ComponentModel.DataAnnotations;

namespace POS.Entities
{

    // OrderTemp
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class OrderTemp
    {
        [Key]
        public int OrdertempId { get; set; } // ordertemp_id (Primary key) (length: 10)
        public string CusId { get; set; } // cus_id (length: 10)
        public string EmpId { get; set; } // emp_id (length: 10)
        public int TableOwned { get; set; } // table_owned (length: 10)
        public System.DateTime Ordertime { get; set; } // ordertime
        public decimal TotalPrice { get; set; } // total_price
        public decimal CustomerPay { get; set; } // customer_pay
        public decimal PayBack { get; set; } // pay_back

        // Reverse navigation

        /// <summary>
        /// Child OrderDetailsTemps where [OrderDetailsTemp].[ordertemp_id] point to this entity (fk_ordertemp_id_orderdetailtemp)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<OrderDetailsTemp> OrderDetailsTemps { get; set; } // OrderDetailsTemp.fk_ordertemp_id_orderdetailtemp




        // Foreign keys


        /// <summary>
        /// Parent Table pointed by [OrderTemp].([TableOwned]) (fk_table_owned_order)
        /// </summary>
        public virtual Table Table { get; set; } // fk_table_owned_order

        public OrderTemp()
        {
            OrderDetailsTemps = new System.Collections.Generic.List<OrderDetailsTemp>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
