// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace POS.Entities
{

    // OrderNote
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class OrderNote
    {
        public string OrdernoteId { get; set; } // ordernote_id (Primary key) (length: 10)
        public string CusId { get; set; } // cus_id (length: 10)
        public string EmpId { get; set; } // emp_id (length: 10)
        public int Ordertable { get; set; } // ordertable
        public System.DateTime Ordertime { get; set; } // ordertime
        public decimal TotalPrice { get; set; } // total_price
        public decimal CustomerPay { get; set; } // customer_pay
        public decimal PayBack { get; set; } // pay_back

        // Reverse navigation

        /// <summary>
        /// Child OrderNoteDetails where [OrderNoteDetails].[ordernote_id] point to this entity (fk_OrderNote)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<OrderNoteDetail> OrderNoteDetails { get; set; } // OrderNoteDetails.fk_OrderNote

        // Foreign keys

        /// <summary>
        /// Parent Customer pointed by [OrderNote].([CusId]) (fk_customerowner)
        /// </summary>
        public virtual Customer Customer { get; set; } // fk_customerowner

        /// <summary>
        /// Parent Employee pointed by [OrderNote].([EmpId]) (fk_employeerespond)
        /// </summary>
        public virtual Employee Employee { get; set; } // fk_employeerespond

        public OrderNote()
        {
            OrderNoteDetails = new System.Collections.Generic.List<OrderNoteDetail>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
