// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace POS.Entities
{

    // OrderDetailsTemp
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class OrderDetailsTemp
    {
        public string OrdertempId { get; set; } // ordertemp_id (Primary key) (length: 10)
        public string ProductId { get; set; } // product_id (Primary key) (length: 10)
        public string ChairId { get; set; } // chair_id (length: 10)
        public string SelectedStats { get; set; } // SelectedStats
        public int Quan { get; set; } // quan
        public string Note { get; set; } // note (length: 500)

        // Foreign keys

        /// <summary>
        /// Parent Chair pointed by [OrderDetailsTemp].([ChairId]) (fk_chair_id_orderdetailtemp)
        /// </summary>
        public virtual Chair Chair { get; set; } // fk_chair_id_orderdetailtemp

        /// <summary>
        /// Parent OrderTemp pointed by [OrderDetailsTemp].([OrdertempId]) (fk_ordertemp_id_orderdetailtemp)
        /// </summary>
        public virtual OrderTemp OrderTemp { get; set; } // fk_ordertemp_id_orderdetailtemp

        /// <summary>
        /// Parent Product pointed by [OrderDetailsTemp].([ProductId]) (fk_product_id_orderdetailtemp)
        /// </summary>
        public virtual Product Product { get; set; } // fk_product_id_orderdetailtemp

        public OrderDetailsTemp()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
