// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6

using System;
using System.ComponentModel.DataAnnotations;
using POS.Entities.CustomEntities;

#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace POS.Entities
{

    // Product
    [Serializable]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class Product
    {
        public string ProductId { get; set; } // product_id (Primary key) (length: 10)
        public string Name { get; set; } // name (length: 50)
        public string Info { get; set; } // info (length: 100)
        public decimal Price { get; set; } // price
        public ProductType Type { get; set; } // is_todrink
        public int Deleted { get; set; } // deleted
        [MaxLength]
        public string ImageLink { get; set; }
        public int Discount { get; set; }

        // Reverse navigation

        /// <summary>
        /// Child OrderNoteDetails where [OrderNoteDetails].[product_id] point to this entity (fk_foodinmenu)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<OrderNoteDetail> OrderNoteDetails { get; set; } // OrderNoteDetails.fk_foodinmenu
        /// <summary>
        /// Child ProductDetails where [ProductDetails].[product_id] point to this entity (fk_productid)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<ProductDetail> ProductDetails { get; set; } // ProductDetails.fk_productid

        public Product()
        {
            OrderNoteDetails = new System.Collections.Generic.List<OrderNoteDetail>();
            ProductDetails = new System.Collections.Generic.List<ProductDetail>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
