// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6

using System;

#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace POS.Entities
{

    // ProductDetails
    [Serializable]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class ProductDetail
    {
        public string PdetailId { get; set; } // pdetail_id (Primary key) (length: 10)
        public string ProductId { get; set; } // product_id (length: 10)
        public string IgdId { get; set; } // igd_id (length: 10)
        public double Quan { get; set; } // quan
        public string UnitUse { get; set; } // unit_use (length: 100)

        // Foreign keys

        /// <summary>
        /// Parent Ingredient pointed by [ProductDetails].([IgdId]) (FK_dbo.ProductDetails_dbo.Ingredient_igd_id)
        /// </summary>
        public virtual Ingredient Ingredient { get; set; } // FK_dbo.ProductDetails_dbo.Ingredient_igd_id

        /// <summary>
        /// Parent Product pointed by [ProductDetails].([ProductId]) (FK_dbo.ProductDetails_dbo.Product_product_id)
        /// </summary>
        public virtual Product Product { get; set; } // FK_dbo.ProductDetails_dbo.Product_product_id

        public ProductDetail()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
