// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace POS.Entities
{

    // ReceiptNoteDetails
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class ReceiptNoteDetail
    {
        public string RnId { get; set; } // rn_id (Primary key) (length: 10)
        public string IgdId { get; set; } // igd_id (Primary key) (length: 10)
        public double Quan { get; set; } // quan
        public decimal ItemPrice { get; set; } // item_price
        public string Note { get; set; } // note (length: 500)

        // Foreign keys

        /// <summary>
        /// Parent Ingredient pointed by [ReceiptNoteDetails].([IgdId]) (FK_dbo.ReceiptNoteDetails_dbo.Ingredient_igd_id)
        /// </summary>
        public virtual Ingredient Ingredient { get; set; } // FK_dbo.ReceiptNoteDetails_dbo.Ingredient_igd_id

        /// <summary>
        /// Parent ReceiptNote pointed by [ReceiptNoteDetails].([RnId]) (FK_dbo.ReceiptNoteDetails_dbo.ReceiptNote_rn_id)
        /// </summary>
        public virtual ReceiptNote ReceiptNote { get; set; } // FK_dbo.ReceiptNoteDetails_dbo.ReceiptNote_rn_id

        public ReceiptNoteDetail()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
