// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace POS.Entities
{

    // SalaryNote
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class SalaryNote
    {
        public string SnId { get; set; } // sn_id (Primary key) (length: 10)
        public string EmpId { get; set; } // emp_id (length: 10)
        public System.DateTime? DatePay { get; set; } // date_pay
        public decimal SalaryValue { get; set; } // salary_value
        public double WorkHour { get; set; } // work_hour
        public int ForMonth { get; set; } // for_month
        public int ForYear { get; set; } // for_year
        public byte IsPaid { get; set; } // is_paid

        // Reverse navigation

        /// <summary>
        /// Child WorkingHistories where [WorkingHistory].[result_salary] point to this entity (fk_salarynote)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<WorkingHistory> WorkingHistories { get; set; } // WorkingHistory.fk_salarynote

        // Foreign keys

        /// <summary>
        /// Parent Employee pointed by [SalaryNote].([EmpId]) (fk_employeeid)
        /// </summary>
        public virtual Employee Employee { get; set; } // fk_employeeid

        public SalaryNote()
        {
            WorkingHistories = new System.Collections.Generic.List<WorkingHistory>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
