// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace POS.Entities
{

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class UpdateLogMass2ReturnModel
    {
        public class ResultSetModel1
        {
            public System.Int32? RowAffected { get; set; }
        }
        public System.Collections.Generic.List<ResultSetModel1> ResultSet1;

        public class ResultSetModel2
        {
            public System.Int32 id { get; set; }
            public System.DateTime date_added { get; set; }
            public System.String comment { get; set; }
            public System.String application_name { get; set; }
            public System.Byte[] last_updated_on { get; set; }
            public System.String extra_data { get; set; }
        }
        public System.Collections.Generic.List<ResultSetModel2> ResultSet2;

    }

}
// </auto-generated>
