// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace POS.Entities
{

    // WareHouse
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class WareHouse
    {
        public string WarehouseId { get; set; } // warehouse_id (Primary key) (length: 10)
        public double? Contain { get; set; } // contain
        public double StandardContain { get; set; }

        // Reverse navigation

        /// <summary>
        /// Child Ingredients where [Ingredient].[warehouse_id] point to this entity (FK_dbo.Ingredient_dbo.WareHouse_warehouse_id)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Ingredient> Ingredients { get; set; } // Ingredient.FK_dbo.Ingredient_dbo.WareHouse_warehouse_id

        public WareHouse()
        {
            Ingredients = new System.Collections.Generic.List<Ingredient>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
